// Tests for CLIShimStore (per-profile `claude-<suffix>` terminal commands) and for the
// backward-compatible `cliCommandSuffix` field on ClaudeProfile.

import Foundation
import XCTest
@testable import ClaudeProfilesCore

final class CLIShimStoreTests: XCTestCase {
    private let fileManager = FileManager.default

    /// A generated shim follows the fixed template exactly and is executable (0755).
    func testWritesShimWithTemplateContentsAndPermissions() throws {
        let bin = try makeTemporaryDirectory().appendingPathComponent("bin")
        defer { try? fileManager.removeItem(at: bin.deletingLastPathComponent()) }
        let profile = makeProfile(name: "Work", suffix: "work", config: "/tmp/Profiles/A/claude-config")

        let result = try CLIShimStore(directory: bin).synchronize(profiles: [profile], executable: "")

        XCTAssertEqual(result.written, ["claude-work"])
        let shim = bin.appendingPathComponent("claude-work")
        XCTAssertEqual(try String(contentsOf: shim, encoding: .utf8), """
        #!/bin/sh
        # Generated by Claude Profiles. Do not edit; the app rewrites this file.
        # Profile: Work (\(profile.id.uuidString))
        export CLAUDE_CONFIG_DIR="/tmp/Profiles/A/claude-config"
        exec claude "$@"

        """)
        XCTAssertEqual(try permissions(of: shim), 0o755)

        // A second pass with the same input changes nothing (idempotent).
        let second = try CLIShimStore(directory: bin).synchronize(profiles: [profile], executable: "")
        XCTAssertEqual(second, CLIShimSyncResult())
    }

    /// Paths with spaces stay one word; a configured executable with spaces is quoted.
    func testQuotesConfigPathAndUnusualExecutable() {
        let profile = makeProfile(
            name: "Line1\nLine2",
            suffix: "x",
            config: "/Users/me/Library/Application Support/Claude \"Profiles\"/claude-config"
        )
        let contents = CLIShimStore.shimContents(for: profile, executable: "/opt/my tools/claude")

        XCTAssertTrue(contents.contains(
            #"export CLAUDE_CONFIG_DIR="/Users/me/Library/Application Support/Claude \"Profiles\"/claude-config""#
        ))
        XCTAssertTrue(contents.contains(#"exec '/opt/my tools/claude' "$@""#))
        XCTAssertTrue(contents.contains("# Profile: Line1 Line2 ("))
        XCTAssertTrue(CLIShimStore.shimContents(for: profile, executable: "~/bin/claude")
            .contains(#"exec ~/bin/claude "$@""#))
    }

    /// Changing the suffix removes the old command and creates the new one.
    func testRenamingSuffixRemovesOldShim() throws {
        let bin = try makeTemporaryDirectory()
        defer { try? fileManager.removeItem(at: bin) }
        var profile = makeProfile(name: "Work", suffix: "old", config: "/tmp/c")
        let store = CLIShimStore(directory: bin)
        try store.synchronize(profiles: [profile], executable: "")

        profile.cliCommandSuffix = "new"
        let result = try store.synchronize(profiles: [profile], executable: "")

        XCTAssertEqual(result.written, ["claude-new"])
        XCTAssertEqual(result.removed, ["claude-old"])
        XCTAssertFalse(fileManager.fileExists(atPath: bin.appendingPathComponent("claude-old").path))
        XCTAssertTrue(fileManager.fileExists(atPath: bin.appendingPathComponent("claude-new").path))
    }

    /// Clearing the suffix or archiving the profile deletes its shim; restoring recreates it.
    func testClearingSuffixAndArchivingRemoveShimAndRestoreRecreatesIt() throws {
        let bin = try makeTemporaryDirectory()
        defer { try? fileManager.removeItem(at: bin) }
        let store = CLIShimStore(directory: bin)
        var profile = makeProfile(name: "Work", suffix: "work", config: "/tmp/c")
        let shim = bin.appendingPathComponent("claude-work")
        try store.synchronize(profiles: [profile], executable: "")

        profile.isArchived = true
        XCTAssertEqual(try store.synchronize(profiles: [profile], executable: "").removed, ["claude-work"])
        XCTAssertFalse(fileManager.fileExists(atPath: shim.path))

        profile.isArchived = false
        XCTAssertEqual(try store.synchronize(profiles: [profile], executable: "").written, ["claude-work"])
        XCTAssertTrue(fileManager.fileExists(atPath: shim.path))

        profile.cliCommandSuffix = nil
        XCTAssertEqual(try store.synchronize(profiles: [profile], executable: "").removed, ["claude-work"])
        XCTAssertFalse(fileManager.fileExists(atPath: shim.path))
    }

    /// A user's own file (no marker) is neither overwritten nor deleted, and is reported.
    func testNeverOverwritesOrDeletesFilesWithoutMarker() throws {
        let bin = try makeTemporaryDirectory()
        defer { try? fileManager.removeItem(at: bin) }
        let userScript = "#!/bin/bash\n# my own wrapper\nexec claude \"$@\"\n"
        try Data(userScript.utf8).write(to: bin.appendingPathComponent("claude-work"))
        try Data(userScript.utf8).write(to: bin.appendingPathComponent("claude-local"))
        let profile = makeProfile(name: "Work", suffix: "work", config: "/tmp/c")

        let result = try CLIShimStore(directory: bin).synchronize(profiles: [profile], executable: "")

        XCTAssertEqual(result.conflicts, ["claude-work"])
        XCTAssertTrue(result.written.isEmpty)
        XCTAssertTrue(result.removed.isEmpty)
        for name in ["claude-work", "claude-local"] {
            XCTAssertEqual(
                try String(contentsOf: bin.appendingPathComponent(name), encoding: .utf8),
                userScript
            )
        }
    }

    /// Generated shims of profiles that no longer exist are removed at the next sync.
    func testRemovesOrphanedGeneratedShims() throws {
        let bin = try makeTemporaryDirectory()
        defer { try? fileManager.removeItem(at: bin) }
        let gone = makeProfile(name: "Gone", suffix: "gone", config: "/tmp/g")
        let store = CLIShimStore(directory: bin)
        try store.synchronize(profiles: [gone], executable: "")

        let result = try store.synchronize(profiles: [], executable: "")

        XCTAssertEqual(result.removed, ["claude-gone"])
    }

    /// The default profile never gets a shim, and invalid suffixes are rejected.
    func testRejectsInvalidSuffixesAndSkipsDefaultProfile() throws {
        for valid in ["a", "work", "Work.2", "a_b-c", "0", String(repeating: "a", count: 41)] {
            XCTAssertTrue(CLIShimStore.isValidSuffix(valid), valid)
        }
        for invalid in ["", "-x", ".x", "_x", "a/b", "a b", "../x", "日本語", String(repeating: "a", count: 42)] {
            XCTAssertFalse(CLIShimStore.isValidSuffix(invalid), invalid)
        }

        let bin = try makeTemporaryDirectory()
        defer { try? fileManager.removeItem(at: bin) }
        var standard = makeProfile(name: "Standard", suffix: "std", config: "/tmp/s")
        standard.isDefault = true
        let invalid = makeProfile(name: "Bad", suffix: "../evil", config: "/tmp/b")

        let result = try CLIShimStore(directory: bin).synchronize(profiles: [standard, invalid], executable: "")

        XCTAssertEqual(result, CLIShimSyncResult())
        XCTAssertEqual(try fileManager.contentsOfDirectory(atPath: bin.path), [])
    }

    /// Duplicate detection only considers other, non-archived profiles.
    func testReportsDuplicateSuffixAmongActiveProfiles() {
        let first = makeProfile(name: "A", suffix: "work", config: "/tmp/a")
        var archived = makeProfile(name: "B", suffix: "old", config: "/tmp/b")
        archived.isArchived = true
        let profiles = [first, archived]

        XCTAssertEqual(CLIShimStore.problem(forSuffix: "work", profileID: nil, among: profiles), .duplicate)
        XCTAssertNil(CLIShimStore.problem(forSuffix: "work", profileID: first.id, among: profiles))
        XCTAssertNil(CLIShimStore.problem(forSuffix: "old", profileID: nil, among: profiles))
        XCTAssertNil(CLIShimStore.problem(forSuffix: "", profileID: nil, among: profiles))
        XCTAssertEqual(CLIShimStore.problem(forSuffix: "a b", profileID: nil, among: profiles), .invalidFormat)
    }

    /// profiles.json written before `cliCommandSuffix` existed still decodes, and a nil
    /// suffix is not written back, so re-saving leaves such files unchanged.
    func testDecodesProfilesJSONWithoutCLIField() throws {
        let data = Data("""
        [{
          "claudeConfigPath": "/tmp/config-1",
          "colorHex": "5968E8",
          "id": "3F2504E0-4F89-11D3-9A0C-0305E82C3301",
          "isArchived": false,
          "isDefault": false,
          "name": "Claude 1",
          "purpose": "実装",
          "userDataPath": "/tmp/profile-1"
        }]
        """.utf8)

        let profiles = try JSONDecoder().decode([ClaudeProfile].self, from: data)

        XCTAssertEqual(profiles.count, 1)
        XCTAssertNil(profiles[0].cliCommandSuffix)
        let encoded = try String(decoding: JSONEncoder().encode(profiles), as: UTF8.self)
        XCTAssertFalse(encoded.contains("cliCommandSuffix"))

        var withSuffix = profiles[0]
        withSuffix.cliCommandSuffix = "one"
        let roundTrip = try JSONDecoder().decode(ClaudeProfile.self, from: JSONEncoder().encode(withSuffix))
        XCTAssertEqual(roundTrip.cliCommandSuffix, "one")
    }

    // MARK: - Helpers

    private func makeProfile(name: String, suffix: String?, config: String) -> ClaudeProfile {
        ClaudeProfile(
            name: name,
            purpose: "test",
            colorHex: "5968E8",
            userDataPath: "/tmp/user-data",
            claudeConfigPath: config,
            cliCommandSuffix: suffix
        )
    }

    private func makeTemporaryDirectory() throws -> URL {
        let url = fileManager.temporaryDirectory
            .appendingPathComponent("CLIShimStoreTests-\(UUID().uuidString)", isDirectory: true)
        try fileManager.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func permissions(of url: URL) throws -> Int {
        let attributes = try fileManager.attributesOfItem(atPath: url.path)
        return try XCTUnwrap(attributes[.posixPermissions] as? NSNumber).intValue
    }
}
