// Per-profile terminal commands ("claude-<suffix>").
//
// For every active, non-default profile that has a CLI command suffix, the app writes a
// tiny POSIX shell script ("shim") into a bin directory (normally ~/.local/bin). Running
// `claude-<suffix>` in a terminal then starts Claude Code with that profile's
// CLAUDE_CONFIG_DIR. The default profile has no shim: plain `claude` already uses it.
//
// Ownership: every generated file carries the marker line "# Generated by Claude
// Profiles". Files without the marker belong to the user and are never overwritten or
// deleted, even when their name collides with a profile's command.
//
// The store is a pure "desired state -> files" synchronizer: callers pass the complete
// profile list after any change (save, rename, clear, archive, restore, app launch) and
// `synchronize` creates, rewrites, and deletes shims so the directory matches. This keeps
// every lifecycle path on one idempotent code path.

import Foundation

/// Why a CLI command suffix cannot be used. Used by the editor to disable saving.
public enum CLICommandSuffixProblem: Equatable, Sendable {
    /// Not of the form `^[A-Za-z0-9][A-Za-z0-9._-]{0,40}$`.
    case invalidFormat
    /// Another non-archived profile already uses the same suffix.
    case duplicate
}

/// Outcome of one synchronization pass.
public struct CLIShimSyncResult: Equatable, Sendable {
    /// Command names whose file was created or rewritten.
    public var written: [String] = []
    /// Command names whose generated file was deleted because no profile wants it anymore.
    public var removed: [String] = []
    /// Command names that could not be written because a file without the ownership
    /// marker (a user's own script) already exists under that name.
    public var conflicts: [String] = []
    /// Command names that two active profiles both asked for; only the first was written.
    public var duplicates: [String] = []

    public init() {}
}

public struct CLIShimStore {
    /// Fixed prefix of every generated command.
    public static let commandPrefix = "claude-"
    /// Marker line that identifies files this app owns.
    public static let ownershipMarker = "# Generated by Claude Profiles"
    /// Executable used when the user has not configured one; resolved through PATH.
    public static let defaultExecutable = "claude"

    /// Suffix grammar: starts with an ASCII letter or digit, then up to 40 more of
    /// letters, digits, ".", "_" or "-". This keeps command names shell-safe (no quoting,
    /// no "/" path escapes, no leading "-" that would look like an option).
    private static let suffixPattern = "^[A-Za-z0-9][A-Za-z0-9._-]{0,40}$"

    /// Characters that can be placed in the shim's `exec` line without quoting.
    private static let unquotedExecutablePattern = "^[A-Za-z0-9_./~+-]+$"

    /// How many leading bytes are inspected for the marker. Generated shims put the marker
    /// on line 2, so a small prefix is enough and large user binaries are never read whole.
    private static let markerScanLimit = 1024

    private let directory: URL
    private let fileManager: FileManager

    /// - Parameter directory: where shims live (production: `~/.local/bin`; tests: a temp dir).
    public init(directory: URL, fileManager: FileManager = .default) {
        self.directory = directory
        self.fileManager = fileManager
    }

    // MARK: - Validation

    /// True when `suffix` matches the allowed command grammar.
    public static func isValidSuffix(_ suffix: String) -> Bool {
        suffix.range(of: suffixPattern, options: .regularExpression) != nil
    }

    /// Checks a suffix typed for `profileID` against the grammar and against the other
    /// non-archived profiles. An empty suffix means "no command" and is always acceptable.
    public static func problem(
        forSuffix suffix: String,
        profileID: UUID?,
        among profiles: [ClaudeProfile]
    ) -> CLICommandSuffixProblem? {
        if suffix.isEmpty {
            return nil
        }
        guard isValidSuffix(suffix) else {
            return .invalidFormat
        }
        let taken = profiles.contains { other in
            other.id != profileID && !other.isArchived && other.cliCommandSuffix == suffix
        }
        return taken ? .duplicate : nil
    }

    // MARK: - Shim contents

    /// The full text of the shim for `profile`, using the fixed template:
    ///
    ///     #!/bin/sh
    ///     # Generated by Claude Profiles. Do not edit; the app rewrites this file.
    ///     # Profile: <name> (<uuid>)
    ///     export CLAUDE_CONFIG_DIR="<absolute claude-config path>"
    ///     exec <claude executable> "$@"
    ///
    /// - Parameter executable: the configured `claude` to run; empty means `claude` via PATH.
    public static func shimContents(for profile: ClaudeProfile, executable: String) -> String {
        // A newline inside the profile name would end the comment and turn the rest of the
        // name into shell code, so line breaks are flattened to spaces.
        let safeName = profile.name
            .components(separatedBy: .newlines)
            .joined(separator: " ")
        return """
        #!/bin/sh
        \(ownershipMarker). Do not edit; the app rewrites this file.
        # Profile: \(safeName) (\(profile.id.uuidString))
        export CLAUDE_CONFIG_DIR="\(doubleQuoteEscaped(profile.claudeConfigPath))"
        exec \(shellWord(forExecutable: executable)) "$@"

        """
    }

    /// Escapes the characters that stay special inside a double-quoted sh string.
    private static func doubleQuoteEscaped(_ value: String) -> String {
        var escaped = ""
        for character in value {
            if "\\\"$`".contains(character) {
                escaped.append("\\")
            }
            escaped.append(character)
        }
        return escaped
    }

    /// The executable as one shell word. Plain values (`claude`, `/opt/homebrew/bin/claude`,
    /// `~/bin/claude`) are written as-is so `~` still expands and the shim matches the
    /// documented template; anything else (spaces, quotes, `$`) is single-quoted.
    private static func shellWord(forExecutable executable: String) -> String {
        let trimmed = executable.trimmingCharacters(in: .whitespacesAndNewlines)
        let value = trimmed.isEmpty ? defaultExecutable : trimmed
        if value.range(of: unquotedExecutablePattern, options: .regularExpression) != nil {
            return value
        }
        return "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Synchronization

    /// Makes the shim directory match `profiles`.
    ///
    /// Wanted: one shim per non-default, non-archived profile with a valid suffix.
    /// - Missing or different generated files are (re)written with mode 0755.
    /// - Generated files (with the marker) named `claude-*` that no profile wants are
    ///   deleted; this covers renames, cleared suffixes, archived and deleted profiles.
    /// - Files without the marker are never modified; a name clash is reported in
    ///   `conflicts` instead.
    /// The directory is created only when at least one shim must be written.
    @discardableResult
    public func synchronize(profiles: [ClaudeProfile], executable: String) throws -> CLIShimSyncResult {
        var result = CLIShimSyncResult()
        let desired = desiredShims(for: profiles, executable: executable, result: &result)
        try writeShims(desired, result: &result)
        try removeUnwantedShims(keeping: Set(desired.map(\.command)), result: &result)
        return result
    }

    /// Step 1: the wanted (command, contents) pairs, in profile order. The first profile
    /// wins a duplicate name; the editor prevents duplicates, but restoring an archived
    /// profile can still collide, which is reported in `duplicates`.
    private func desiredShims(
        for profiles: [ClaudeProfile],
        executable: String,
        result: inout CLIShimSyncResult
    ) -> [(command: String, contents: String)] {
        var desired: [(command: String, contents: String)] = []
        for profile in profiles where !profile.isDefault && !profile.isArchived {
            guard let suffix = profile.cliCommandSuffix, Self.isValidSuffix(suffix) else {
                continue
            }
            let command = Self.commandPrefix + suffix
            if desired.contains(where: { $0.command == command }) {
                result.duplicates.append(command)
                continue
            }
            desired.append((command, Self.shimContents(for: profile, executable: executable)))
        }
        return desired
    }

    /// Step 2: write shims that are missing or stale (contents or mode differ). Existing
    /// files without the marker are left alone and reported in `conflicts`. The directory
    /// is created only when there is something to write.
    private func writeShims(
        _ desired: [(command: String, contents: String)],
        result: inout CLIShimSyncResult
    ) throws {
        if !desired.isEmpty {
            try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
        }
        for (command, contents) in desired {
            let url = directory.appendingPathComponent(command)
            let exists = fileManager.fileExists(atPath: url.path) || isSymbolicLink(url)
            if exists && !isOwned(url) {
                result.conflicts.append(command)
                continue
            }
            if exists && isUpToDate(url, contents: contents) {
                continue
            }
            try Data(contents.utf8).write(to: url, options: .atomic)
            try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
            result.written.append(command)
        }
    }

    /// Step 3: delete generated `claude-*` files that no profile wants anymore (renamed,
    /// cleared, archived or deleted profiles). User files without the marker are skipped.
    /// A missing directory means there is nothing to clean up.
    private func removeUnwantedShims(keeping wanted: Set<String>, result: inout CLIShimSyncResult) throws {
        let existing = (try? fileManager.contentsOfDirectory(atPath: directory.path)) ?? []
        for name in existing.sorted() where name.hasPrefix(Self.commandPrefix) && !wanted.contains(name) {
            let url = directory.appendingPathComponent(name)
            guard isOwned(url) else {
                continue
            }
            try fileManager.removeItem(at: url)
            result.removed.append(name)
        }
    }

    // MARK: - Login shell PATH

    /// Whether `directory` is on the PATH of the user's login shell, or nil when that
    /// cannot be determined. Runs `/bin/zsh -lc 'printf %s "$PATH"'`: zsh is the macOS
    /// default shell and `-l` loads the same profile files as a new Terminal window, so the
    /// answer matches what the user will see. Blocking; call it off the main thread.
    public static func isDirectoryOnLoginShellPath(_ directory: URL) -> Bool? {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/zsh")
        process.arguments = ["-lc", #"printf %s "$PATH""#]
        let output = Pipe()
        process.standardOutput = output
        process.standardError = FileHandle.nullDevice
        process.standardInput = FileHandle.nullDevice
        do {
            try process.run()
        } catch {
            return nil
        }
        let data = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            return nil
        }
        // PATH entries may carry a trailing slash; compare standardized paths.
        let target = directory.standardizedFileURL.path
        return String(decoding: data, as: UTF8.self)
            .split(separator: ":")
            .contains { URL(fileURLWithPath: String($0)).standardizedFileURL.path == target }
    }

    // MARK: - File inspection

    /// True only for a regular file whose first lines contain the ownership marker.
    /// Symbolic links and directories are never considered owned, so they are never
    /// rewritten or deleted.
    func isOwned(_ url: URL) -> Bool {
        guard !isSymbolicLink(url),
              let attributes = try? fileManager.attributesOfItem(atPath: url.path),
              attributes[.type] as? FileAttributeType == .typeRegular,
              let handle = try? FileHandle(forReadingFrom: url) else {
            return false
        }
        defer { try? handle.close() }
        let head = (try? handle.read(upToCount: Self.markerScanLimit)) ?? Data()
        let text = String(decoding: head, as: UTF8.self)
        return text.components(separatedBy: "\n").contains { $0.hasPrefix(Self.ownershipMarker) }
    }

    private func isSymbolicLink(_ url: URL) -> Bool {
        let attributes = try? fileManager.attributesOfItem(atPath: url.path)
        return attributes?[.type] as? FileAttributeType == .typeSymbolicLink
    }

    /// True when the file already has exactly `contents` and mode 0755.
    private func isUpToDate(_ url: URL, contents: String) -> Bool {
        (try? String(contentsOf: url, encoding: .utf8)) == contents && permissions(of: url) == 0o755
    }

    private func permissions(of url: URL) -> Int? {
        let attributes = try? fileManager.attributesOfItem(atPath: url.path)
        return (attributes?[.posixPermissions] as? NSNumber)?.intValue
    }
}
